# Generated by Django 5.0.4 on 2024-05-17 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='WishlistItem',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product')},
        ),
    ]
